# Generated by Django 4.1.13 on 2024-08-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, unique=True, verbose_name='عنوان در دسته بندی')),
                ('url_title', models.URLField(verbose_name='')),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(verbose_name='حذف شده / نشده')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان تورنومنت')),
                ('mode', models.CharField(max_length=10, verbose_name='حالت بازی')),
                ('prize', models.IntegerField(verbose_name='مقدار جایزه')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تورنومنت')),
                ('ticketamount', models.IntegerField(verbose_name='هزینه ورودی')),
                ('link', models.URLField(verbose_name='ادرس url ')),
                ('image', models.FileField(upload_to='image', verbose_name='عکس تورنومنت')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(verbose_name='فعال شده / نشده')),
                ('is_delete', models.BooleanField(verbose_name='حذف شده / نشده')),
                ('category', models.ManyToManyField(related_name='tournament_categories', to='Tournaments.category', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'تورنومنت',
                'verbose_name_plural': 'تورنومنت ها',
            },
        ),
    ]
