# Generated by Django 4.1.13 on 2024-09-02 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='یوزر برنده'),
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='category',
        ),
        migrations.AddField(
            model_name='tournament',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_categories', to='Tournaments.category', verbose_name='دسته بندی ها'),
        ),
    ]
