# Generated by Django 4.1.13 on 2024-08-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='link',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='mode',
            field=models.CharField(max_length=15, verbose_name='حالت بازی'),
        ),
    ]
