# Generated by Django 4.1.13 on 2024-08-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0002_remove_tournament_link_alter_tournament_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=15, unique=True, verbose_name='عنوان در دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url_title',
            field=models.URLField(db_index=True, max_length=40, verbose_name='عنوان در url'),
        ),
    ]
