# Generated by Django 4.1.13 on 2024-08-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0003_alter_category_title_alter_category_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال شده / نشده'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url_title',
            field=models.CharField(db_index=True, max_length=40, verbose_name='عنوان در url'),
        ),
    ]
