# Generated by Django 4.1.13 on 2024-08-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0004_alter_category_is_active_alter_category_url_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='عنوان در دسته بندی'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='image',
            field=models.ImageField(upload_to='tournaments_image', verbose_name='عکس تورنومنت'),
        ),
    ]
