# Generated by Django 4.1.13 on 2024-08-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0005_upload_alter_category_title_alter_tournament_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
