# Generated by Django 4.1.13 on 2024-08-30 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0006_alter_upload_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='image',
            new_name='upload',
        ),
    ]
