# Generated by Django 4.1.13 on 2024-08-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال / غیرفعال'),
        ),
    ]
