# Generated by Django 4.1.13 on 2024-08-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0002_registration_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='is_active',
            field=models.BooleanField(verbose_name='فعال / غیرفعال'),
        ),
    ]
